"""Per-engine URL templates and CSS selectors.

Selectors are best effort and WILL drift. Run `python cli.py doctor` after a
fetch to see which engines parse to zero results, then edit the spec here and
re-run `score`; no re-querying is needed because raw HTML is cached.

Each selector field is a list; the first selector that matches wins.
Locale: English language, Netherlands region.
"""

SPECS = {
    "google": {
        "url": "https://www.google.com/search?q={q}&hl=en&gl=nl&pws=0&num=10",
        "consent": ["button#L2AGLb", "button:has-text('Accept all')"],
        "ready": ["#search", "#rso"],
        "result": ["div#rso div.g", "div#search div.g", "div#rso div.MjjYud"],
        "title": ["h3"],
        "link": ["a[href^='http']"],
        "cite": ["cite"],
        "skip_hosts": ["support.google.com"],
        "snippet": ["div.VwiC3b", "div[data-sncf]", "div.IsZvec"],
        "ads": ["#tads div[data-text-ad]", "#tads", "#tadsb"],
        "answer": ["div.IZ6rdc", "div.vk_c", "div.kp-wholepage", "div[data-attrid^='kc:']",
                   "div.card-section", "div[data-attrid='wa:/description']", "#wp-tabs-container"],
        "rewrite": ["#fprsl", "#fprs"],
    },
    "bing": {
        "url": "https://www.bing.com/search?q={q}&setlang=en&cc=NL&mkt=en-NL",
        "consent": ["#bnp_btn_accept", "button:has-text('Accept')"],
        "ready": ["#b_results"],
        "result": ["li.b_algo"],
        "title": ["h2 a", "h2"],
        "link": ["h2 a"],
        "snippet": ["div.b_caption p", "p.b_lineclamp2", "p.b_lineclamp3", "div.b_caption"],
        "ads": ["li.b_ad"],
        "answer": [".b_ans", ".dict_wp", ".b_focusTextLarge", ".b_entityTP", "#b_context .b_entityTP"],
        "rewrite": ["#sp_requery", ".b_fcl"],
    },
    "duckduckgo": {
        "url": "https://duckduckgo.com/?q={q}&kl=nl-en&ia=web",
        "consent": [],
        "ready": ["article[data-testid='result']", "#links"],
        "result": ["article[data-testid='result']", "#links div.result"],
        "title": ["h2 a", "h2", "a.result__a"],
        "link": ["h2 a", "a.result__a"],
        "snippet": ["div[data-result='snippet']", "[data-testid='result-snippet']", "a.result__snippet"],
        "ads": ["[data-testid='ad']", "li[data-layout='ad']"],
        "answer": ["[data-testid='about']", "[data-testid='zci']", "#zci-answer", ".module--answer", "div.zci"],
        "rewrite": ["#did_you_mean", ".js-spelling-suggestion", "[data-testid='spelling']"],
    },
    "startpage": {
        "url": "https://www.startpage.com/do/search?q={q}&language=english&lui=english",
        "consent": [],
        "ready": ["div.result", "#main"],
        "result": ["div.result", "section.w-gl div.result"],
        "title": ["h2", "h3", "a.result-title"],
        "link": ["a.result-title", "a.result-link", "a[href^='http']"],
        "snippet": ["p.description", "p.w-gl__description"],
        "ads": ["div.sponsored", ".w-gl--sponsored"],
        "answer": [".infobox", "#infobox", "div.kg", "div.w-gl--answer"],
        "rewrite": [".spelling-suggestion", "#spell-suggestion"],
    },
    "metager": {
        "url": "https://metager.org/meta/meta.ger3?eingabe={q}&focus=web&lang=en",
        "consent": [],
        "ready": ["div.result", "#results"],
        "result": ["div.result"],
        "title": [".result-title a", "h2 a", "h2"],
        "link": [".result-title a", "a.result-link", "a[href^='http']"],
        "snippet": [".result-description", "div.result-description"],
        "ads": [".ad", ".result.ad"],
        "answer": [".quicktips", ".quicktip", "#quicktips", ".infobox"],
        "rewrite": [],
    },
    "ecosia": {
        "url": "https://www.ecosia.org/search?q={q}&language=en",
        "consent": ["button:has-text('Accept')", "button:has-text('Agree')"],
        "ready": ["[data-test-id='organic-result']", "main"],
        "result": ["[data-test-id='organic-result']", "[data-test-id='mainline-result-web']", "article"],
        "title": ["a[data-test-id='result-title']", "h2", "a"],
        "link": ["a[data-test-id='result-link']", "a[data-test-id='result-title']", "a[href^='http']"],
        "snippet": ["[data-test-id='result-snippet']", "p"],
        "ads": ["[data-test-id='ad']", "[data-test-id='mainline-result-ad']"],
        "answer": ["[data-test-id='infobox']", "[data-test-id='instant-answer']", "[data-test-id='entity-card']"],
        "rewrite": ["[data-test-id='spell-suggestion']"],
    },
    "swisscows": {
        "url": "https://swisscows.com/en/web?query={q}",
        "consent": ["button:has-text('Accept')"],
        "ready": ["article.item-web", ".web-results"],
        "result": ["article.web-page", "article.item-web", ".item-web"],
        "title": ["h1.title", "h2 a", "h2"],
        "link": ["a.mainlink", "h2 a", "a[href^='http']"],
        "snippet": ["p.description", "p.item-description", "p"],
        "ads": [".ad", ".sponsored"],
        "answer": [".infobox", ".instant-answer"],
        "rewrite": [],
    },
    "qwant": {
        "url": "https://www.qwant.com/?q={q}&t=web&l=en",
        "consent": ["button:has-text('Accept')", "button:has-text('Agree')"],
        "ready": ["[data-testid='webResult']", "#__next"],
        "result": ["[data-testid='webResult']", "div[data-testid='sectionWeb'] > div"],
        "title": ["a[data-testid='serTitle']", "h2", "a"],
        "link": ["a[data-testid='serTitle']", "a[href^='http']"],
        "snippet": ["[data-testid='webResultDescription']", "div[class*='description']", "p"],
        "ads": ["[data-testid='adResult']", "[data-testid='sectionAds']"],
        "answer": ["[data-testid='instantAnswer']", "[data-testid='infobox']", "[data-testid='wikipedia']"],
        "rewrite": ["[data-testid='spellCheck']"],
    },
    "yandex": {
        "url": "https://yandex.com/search/?text={q}&lr=118",
        "consent": [],
        "ready": ["li.serp-item", "#search-result"],
        "result": ["div.Organic", "li.serp-item:not(.serp-adv-item)", "li.serp-item"],
        "title": [".OrganicTitle-LinkText", "h2", "a"],
        "link": ["a.OrganicTitle-Link", "a.Link[href^='http']", "a[href^='http']"],
        "snippet": [".OrganicText", ".TextContainer", ".ExtendedText"],
        "ads": ["li.serp-adv-item", ".Organic_withLabel", ".AdvLabel"],
        "answer": [".Fact", ".Entity", ".Wizard", ".serp-list__wizard"],
        "rewrite": [".Misspell", ".misspell"],
    },
    "mojeek": {
        "url": "https://www.mojeek.com/search?q={q}&lb=en&arc=nl",
        "consent": [],
        "ready": ["ul.results-standard", "body"],
        "result": ["ul.results-standard > li", "ul.results-standard li"],
        "title": ["a.title", "h2 a", "h2"],
        "link": ["a.title", "a.ob", "a[href^='http']"],
        "snippet": ["p.s", "p"],
        "ads": [],
        "answer": [".infobox", ".snippet.answer", "div.answer"],
        "rewrite": [".did-you-mean", ".spell"],
    },
    "brave": {
        "url": "https://search.brave.com/search?q={q}&source=web&country=nl",
        "consent": [],
        "ready": ["#results", "div.snippet"],
        "result": ["#results div.snippet[data-type='web']", "div.snippet[data-type='web']", "div.snippet"],
        "title": [".title", ".snippet-title", "a"],
        "link": ["a[href^='http']"],
        "snippet": [".snippet-description", ".content", ".generic-snippet"],
        "ads": ["div.snippet[data-type='ad']", ".ad"],
        "answer": ["#infobox", ".infobox", ".answer", "#summarizer", ".chatllm", ".card"],
        "rewrite": ["#altered-query", ".altered-query"],
    },
    "marginalia": {
        "url": "https://search.marginalia.nu/search?query={q}",
        "consent": [],
        "ready": [".search-result", "#results", "body"],
        "result": ["section.search-result", ".search-result"],
        "title": ["h2 a", ".title", "h2"],
        "link": ["h2 a", "a[href^='http']"],
        "snippet": ["p.description", ".description", "p"],
        "ads": [],
        "answer": [],
        "rewrite": [],
    },
}

# Substrings on the page that mean a bot check is blocking results.
CAPTCHA_MARKERS = [
    "unusual traffic", "captcha", "verify you are human", "are you a robot",
    "not a robot", "automated queries", "access denied", "checking your browser",
    "confirm you are human", "too many requests",
]

# Visible-text patterns indicating the engine rewrote the query.
REWRITE_TEXT = [
    r"showing results for", r"including results for", r"search instead for",
    r"search only for", r"no results found for", r"did you mean",
    r"results for .{1,80}\. ?search for",
]
